<a href="https://colab.research.google.com/github/fereshtehdehkhoda/Example13-linear-equations/blob/main/linear_equations_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# linear equations

In [ ]:
# x1?

In [ ]:
import numpy as np

In [ ]:
A=np.array([[1,3,5],[2,4,0],[0,7,9]])
A

array([[1, 3, 5],
       [2, 4, 0],
       [0, 7, 9]])

In [ ]:
b=np.array([[12],[-1],[-2]])
b

array([[12],
       [-1],
       [-2]])

In [ ]:
#Ax=b
x=np.linalg.solve(A,b)
x

array([[ 8.92307692],
       [-4.71153846],
       [ 3.44230769]])

In [ ]:
#x1=8.92307692
#x2=-4.71153846
#x3=3.44230769